"""add is_ensemble_only to musician_profile

Revision ID: 72a0cf37fe62
Revises: 3b1c2d3e4f5g
Create Date: 2026-09-22 21:53:07.811520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72a0cf37fe62'
down_revision: Union[str, None] = '3b1c2d3e4f5g'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'location_city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('booking', 'share_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_booking_complaint_status'), table_name='booking_complaint')
    op.alter_column('booking_review', 'is_final',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('uq_booking_review_final'), table_name='booking_review', postgresql_where='(is_final IS TRUE)')
    op.create_index(op.f('ix_booking_review_booking_id'), 'booking_review', ['booking_id'], unique=False)
    op.alter_column('contractor_profile', 'contract_template_body',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contractor_profile', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('draft', 'pending_review', 'published', 'rejected', name='profilestatus'),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.drop_index(op.f('uq_contractor_document_number_normalized'), table_name='contractor_profile', postgresql_where="((document_number IS NOT NULL) AND (btrim((document_number)::text) <> ''::text))")
    op.drop_constraint(op.f('contractor_profile_user_id_fkey'), 'contractor_profile', type_='foreignkey')
    op.create_foreign_key(None, 'contractor_profile', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('musician_profile', 'songs',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('musician_profile', 'repertoire',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('musician_profile', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('draft', 'pending_review', 'published', 'rejected', name='profilestatus'),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.drop_index(op.f('uq_musician_profile_slug'), table_name='musician_profile', postgresql_where='(slug IS NOT NULL)')
    op.drop_index(op.f('uq_musician_profile_slug_lower'), table_name='musician_profile', postgresql_where="((slug IS NOT NULL) AND (btrim((slug)::text) <> ''::text))")
    op.drop_index(op.f('uq_musician_profile_stage_name_lower'), table_name='musician_profile')
    op.create_index(op.f('ix_musician_profile_slug'), 'musician_profile', ['slug'], unique=True)
    op.drop_index(op.f('ix_support_ticket_status'), table_name='support_ticket')
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('uq_user_email_verification_token'), table_name='user', postgresql_where='(email_verification_token IS NOT NULL)')
    op.drop_index(op.f('uq_user_password_reset_token'), table_name='user', postgresql_where='(password_reset_token IS NOT NULL)')
    op.drop_index(op.f('uq_user_username_lower'), table_name='user', postgresql_where="((username IS NOT NULL) AND (btrim((username)::text) <> ''::text))")
    op.create_index(op.f('ix_user_email_verification_token'), 'user', ['email_verification_token'], unique=True)
    op.create_index(op.f('ix_user_password_reset_token'), 'user', ['password_reset_token'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_password_reset_token'), table_name='user')
    op.drop_index(op.f('ix_user_email_verification_token'), table_name='user')
    op.create_index(op.f('uq_user_username_lower'), 'user', [sa.literal_column('lower(btrim(username::text))')], unique=True, postgresql_where="((username IS NOT NULL) AND (btrim((username)::text) <> ''::text))")
    op.create_index(op.f('uq_user_password_reset_token'), 'user', ['password_reset_token'], unique=True, postgresql_where='(password_reset_token IS NOT NULL)')
    op.create_index(op.f('uq_user_email_verification_token'), 'user', ['email_verification_token'], unique=True, postgresql_where='(email_verification_token IS NOT NULL)')
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_support_ticket_status'), 'support_ticket', ['status'], unique=False)
    op.drop_index(op.f('ix_musician_profile_slug'), table_name='musician_profile')
    op.create_index(op.f('uq_musician_profile_stage_name_lower'), 'musician_profile', [sa.literal_column('lower(btrim(stage_name::text))')], unique=True)
    op.create_index(op.f('uq_musician_profile_slug_lower'), 'musician_profile', [sa.literal_column('lower(btrim(slug::text))')], unique=True, postgresql_where="((slug IS NOT NULL) AND (btrim((slug)::text) <> ''::text))")
    op.create_index(op.f('uq_musician_profile_slug'), 'musician_profile', ['slug'], unique=True, postgresql_where='(slug IS NOT NULL)')
    op.alter_column('musician_profile', 'status',
               existing_type=sa.Enum('draft', 'pending_review', 'published', 'rejected', name='profilestatus'),
               type_=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('musician_profile', 'repertoire',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('musician_profile', 'songs',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.drop_constraint(None, 'contractor_profile', type_='foreignkey')
    op.create_foreign_key(op.f('contractor_profile_user_id_fkey'), 'contractor_profile', 'user', ['user_id'], ['id'])
    op.create_index(op.f('uq_contractor_document_number_normalized'), 'contractor_profile', [sa.literal_column("upper(replace(btrim(document_number::text), ' '::text, ''::text))")], unique=True, postgresql_where="((document_number IS NOT NULL) AND (btrim((document_number)::text) <> ''::text))")
    op.alter_column('contractor_profile', 'status',
               existing_type=sa.Enum('draft', 'pending_review', 'published', 'rejected', name='profilestatus'),
               type_=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('contractor_profile', 'contract_template_body',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_booking_review_booking_id'), table_name='booking_review')
    op.create_index(op.f('uq_booking_review_final'), 'booking_review', ['booking_id'], unique=True, postgresql_where='(is_final IS TRUE)')
    op.alter_column('booking_review', 'is_final',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_booking_complaint_status'), 'booking_complaint', ['status'], unique=False)
    op.alter_column('booking', 'share_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('booking', 'location_city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
