"""fase6_schema_cleanup

Revision ID: 75602b2dab88
Revises: 72a0cf37fe62
Create Date: 2026-10-01 00:43:10.731285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '75602b2dab88'
down_revision: Union[str, None] = '72a0cf37fe62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'pending_advance_amount')
    op.drop_column('booking', 'advance_amount')
    op.drop_index(op.f('ix_booking_complaint_status'), table_name='booking_complaint')
    op.drop_index(op.f('uq_booking_review_final'), table_name='booking_review', postgresql_where='(is_final IS TRUE)')
    op.drop_index(op.f('uq_contractor_document_number_normalized'), table_name='contractor_profile', postgresql_where="((document_number IS NOT NULL) AND (btrim((document_number)::text) <> ''::text))")
    op.drop_index(op.f('uq_musician_profile_slug'), table_name='musician_profile', postgresql_where='(slug IS NOT NULL)')
    op.drop_index(op.f('uq_musician_profile_slug_lower'), table_name='musician_profile', postgresql_where="((slug IS NOT NULL) AND (btrim((slug)::text) <> ''::text))")
    op.drop_index(op.f('uq_musician_profile_stage_name_lower'), table_name='musician_profile')
    op.drop_index(op.f('ix_support_ticket_status'), table_name='support_ticket')
    op.drop_constraint(op.f('uploaded_file_filename_key'), 'uploaded_file', type_='unique')
    op.create_index(op.f('ix_uploaded_file_filename'), 'uploaded_file', ['filename'], unique=True)
    op.drop_index(op.f('uq_user_email_verification_token'), table_name='user', postgresql_where='(email_verification_token IS NOT NULL)')
    op.drop_index(op.f('uq_user_password_reset_token'), table_name='user', postgresql_where='(password_reset_token IS NOT NULL)')
    op.drop_index(op.f('uq_user_username_lower'), table_name='user', postgresql_where="((username IS NOT NULL) AND (btrim((username)::text) <> ''::text))")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_user_username_lower'), 'user', [sa.literal_column('lower(btrim(username::text))')], unique=True, postgresql_where="((username IS NOT NULL) AND (btrim((username)::text) <> ''::text))")
    op.create_index(op.f('uq_user_password_reset_token'), 'user', ['password_reset_token'], unique=True, postgresql_where='(password_reset_token IS NOT NULL)')
    op.create_index(op.f('uq_user_email_verification_token'), 'user', ['email_verification_token'], unique=True, postgresql_where='(email_verification_token IS NOT NULL)')
    op.drop_index(op.f('ix_uploaded_file_filename'), table_name='uploaded_file')
    op.create_unique_constraint(op.f('uploaded_file_filename_key'), 'uploaded_file', ['filename'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_support_ticket_status'), 'support_ticket', ['status'], unique=False)
    op.create_index(op.f('uq_musician_profile_stage_name_lower'), 'musician_profile', [sa.literal_column('lower(btrim(stage_name::text))')], unique=True)
    op.create_index(op.f('uq_musician_profile_slug_lower'), 'musician_profile', [sa.literal_column('lower(btrim(slug::text))')], unique=True, postgresql_where="((slug IS NOT NULL) AND (btrim((slug)::text) <> ''::text))")
    op.create_index(op.f('uq_musician_profile_slug'), 'musician_profile', ['slug'], unique=True, postgresql_where='(slug IS NOT NULL)')
    op.create_index(op.f('uq_contractor_document_number_normalized'), 'contractor_profile', [sa.literal_column("upper(replace(btrim(document_number::text), ' '::text, ''::text))")], unique=True, postgresql_where="((document_number IS NOT NULL) AND (btrim((document_number)::text) <> ''::text))")
    op.create_index(op.f('uq_booking_review_final'), 'booking_review', ['booking_id'], unique=True, postgresql_where='(is_final IS TRUE)')
    op.create_index(op.f('ix_booking_complaint_status'), 'booking_complaint', ['status'], unique=False)
    op.add_column('booking', sa.Column('advance_amount', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('booking', sa.Column('pending_advance_amount', sa.NUMERIC(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
